name: Cypress E2E tests
on:
  pull_request:
    branches:
      - master
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'

      - name: Install
        run: yarn --immutable

      - name: Typecheck
        run: yarn typecheck

      - name: Lint
        run: yarn lint

      - name: Cypress run
        # Uses the official Cypress GitHub action https://github.com/cypress-io/github-action
        uses: cypress-io/github-action@v5
        with:
          install-command: yarn --immutable
          browser: chrome
          start: yarn run start-e2e
          wait-on: 'http://localhost:3000' # Waits for above
          wait-on-timeout: 120 # Waits for 2 minutes
          # Records to Cypress Dashboard
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # created by the GH Action automatically
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
